server:
  port: 8080
  servlet:
    context-path: /solrapi
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    servlet:
      load-on-startup: 1
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
  servlet:
    multipart:
      file-size-threshold: 16MB
      max-file-size: 2GB
      max-request-size: 2GB
#  data:
#    mongodb:
#      uri: mongodb://ddi_user:V5f3SThe@193.62.55.69:30304/admin
#      database: ddi_db



